### ISSUE TITLE
Support for private Bitbucket/Stash repository URLs

### ISSUE THREAD

**Issue by jpierson** [qinezh/vscode-gitlink#10]
Are private repository sites supported through any type of configurable setting for the template of the URL. It would be nice if there was a way to set a template string format for the URL patterns through configuration to support this. Currently one of my clients is using a private Stash installation which I understand is based off of BitBucket but has a custom domain and perhaps some differences in URL layout. I could see however how this feature could be applied to private GitHub enterprise installations or others like it. Perhaps this is already possible and if not it would be a cool feature to consider.

**Comment by qinezh** [comment]
As I want to make the extension simple and work out-of-the-box, configuration setting is out of my scope currently.
