### ISSUE TITLE
Feature Request: Add configuration option for remote name

### ISSUE THREAD

**Issue by Brocco** [qinezh/vscode-gitlink#11]
If you have multiple remotes defined you're always prompted to select which to use.

Providing an option via configuration to supply a default name to use when multiple for remotes are discovered.

For instance most (if not all) of my repos have 2 remotes (origin & upstream) I would like to specify which remote to use in this scenario.

```
"gitLink.remote": "upstream"
```

**Comment by qinezh** [comment]
@Brocco could you try the new release of this extension? Currently the feature you request is already supported. Thanks your suggestion.

Enable in workspace level: add `"gitlink.defaultRemote": "upstream"` in `.vscode/settings.json` under the root of your workspace.

Enable in global level: toggle the preference of vscode, and add `"gitlink.defaultRemote": "upstream"` in User Settings.

**Comment by Brocco** [comment]
BEAUTIFUL! Works as expected... THANKS!

**Comment by qinezh** [comment]
cc @manekinekko @wardbell @mgechev, as you may need this feature too.
