### ISSUE TITLE
Copy link functionality not working in Linux

### ISSUE THREAD

**Issue by redders6600** [qinezh/vscode-gitlink#13]
I was having a problem with the ["open in github"](https://github.com/ziyasal/vscode-open-in-github/issues/53) package that does a similar thing to yours where I couldn't copy the link to my clipboard on Ubuntu 16.04 and was hoping this package would work instead, but it doesn't seem to.

The "go to" functionality works fine, but copying to clipboard doesn't work at all - given it's a problem for multiple packages, this may be linked to some more fundamental issue with either vscode or electron?

**Comment by qinezh** [comment]
Hi @redders6600 , the root cause should be:

> 'xclip' - which this package uses on Linux - isn't installed by default on Debian. A quick 'apt-get install xclip' 

see https://github.com/xavi-/node-copy-paste/issues/56

Could you help have a try? As I don't have Linux desktop now 😸

**Comment by redders6600** [comment]
Yep, that does it! Thanks for your help!
As this issue isn't specific to your package I'll close it.
