### ISSUE TITLE
URL should escape `#` character

### ISSUE THREAD

**Issue by redders6600** [qinezh/vscode-gitlink#14]
Many of the branches I work with contain a `#` to reference the issue number they address, which is perfectly valid within git.

The link this generates is looks like the following:
```
https://github.com/user/repo/blob/branch-for-issue-#123/path/to/file.js#L101
```

It should in fact be url encoded:
```
https://github.com/user/repo/blob/branch-for-issue-%23123/path/to/file.js#L101
```

Not sure if this is a problem for other symbols, or just for the `#` due to the fact it's being used for the line number at the end?

**Comment by qinezh** [comment]
@redders6600 Thanks for reporting this issue. I have just fixed it and release a new version, could you help to try the latest version(v0.4.3) to check if the issue is resolved?

**Comment by redders6600** [comment]
@qinezh - yes, updated fine and works perfectly now.
Kudos for fixing this so quickly!
