### ISSUE TITLE
GitLab links are incorrect

### ISSUE THREAD

**Issue by MLefebvreICO** [qinezh/vscode-gitlink#17]
The resulting link for GitLab is incorrect.

**Steps to reproduce**

- Go into `VSCode Settings`
- Set the `Default Remote` to `https://someorganization.githost.io/Some-Root/someproject/tree/`
- Go into a file, select multiple lines and right click and do `Goto online link`

**Current behavior** : It goes to the correct file to line 1.

**Expected bahavior** : It should open up the correct file at the chosen line.

My guess is that GitLab doesn't support line ranges in the URL (or not in that format) since removing the ending part seems to make it work(from `#L63-L66` to `#L63`).

**Fix proposed** : Have a setting to choose which Git provider we are using and when we selected GitLab only return the start line

**Comment by MLefebvreICO** [comment]
Actually the way to do it in GitLab seems to be going from `#L63-L66` to `#L63-66`

**Comment by qinezh** [comment]
@MLefebvreICO it looks hard to guess whether the host is GitLab from this default remote origin URL, currently this extension doesn't support githost.io...

**Comment by MLefebvreICO** [comment]
@qinezh Actually, `githost` is a service provided by the official GitLab team so it would have made sense to support it.

I said "would have", because I just checked and they plan to retire `githost` to only focus on GitLab on June 1 2019, so since it is not future proof that make sense to not support it.

**Comment by falkben** [comment]
Is there any chance we could get a setting to specify whether the default host is a self hosted gitlab based and would need the line number formatting as specified by @MLefebvreICO?  Thanks!
