### ISSUE TITLE
It's very hard to setup

### ISSUE THREAD

**Issue by lflucasferreira** [qinezh/vscode-gitlink#21]
I use Gitlab and I don't understand how to set up the extension. When I try to open a link it points me to the project without the port and project name. Maybe you should detail a little bit more on how to get started.

**Comment by qinezh** [comment]
For most cases, there's no need to set up the extension, and it can be used out of box.

Can you please clarify the expected link and the actual link? Then I can take a look if it's a bug or unsupported scenario. Thanks.

**Comment by qinezh** [comment]
Closed this issue as there's no detail information.
