### ISSUE TITLE
Feature request: inverse operation, start with a GitHub URL which contains hash line number(s), and open the file in VSCode at the designated line / code selection

### ISSUE THREAD

**Issue by danielweck** [qinezh/vscode-gitlink#24]
Hello, great extension, thank you!
Very useful for code peer reviews over Slack / instant messaging, to exchange URLs whilst working locally from VSCode.
However the inverse functionality would be very useful too.

For example I would like to be able to copy such URL: `https://github.com/qinezh/vscode-gitlink/blob/b4a63e250a05df070b861c1cf2c956a983843ed3/src/extension.ts#L7-L8`

https://github.com/qinezh/vscode-gitlink/blob/b4a63e250a05df070b861c1cf2c956a983843ed3/src/extension.ts#L7-L8

...and to show `src/extension.ts` in VSCode with the code selection line 7-8 (extracted from the URL `#L7-L8`).

Any thoughts?

**Comment by qinezh** [comment]
@danielweck  Oh sorry for the late response. Thanks for your suggestion :) 
Your idea looks good, however it would be a little bit tricky, as your local git might in another branch with some unstaged changes, so it's hardly switch to the git commit provided by the pasted URL without side effect.

If you have better idea about the solution to implement it, feel free to let me know 😄

**Comment by qinezh** [comment]
Closed as there's no more discussion.
