### ISSUE TITLE
Unable to got to online link when on a local branch

### ISSUE THREAD

**Issue by IndrekV** [qinezh/vscode-gitlink#25]
When you have not pushed the local branch and want to share or go to a link online it tries to open a link for the nonexistent branch. I would add a fallback to the branch that the current branch was originated.

Step by step it would mean:

- Check if the remote branch exists
  - If exists action as usual
  - If it does not exist in remote point to the same file in the originating branch
git command to get the originating branch
```
git show-branch \
| sed "s/].*//" \
| grep "\*" \
| grep -v "$(git rev-parse --abbrev-ref HEAD)" \
| head -n1 \
| sed "s/^.*\[//" 
```

Source: https://stackoverflow.com/a/17843908

**Comment by qinezh** [comment]
@IndrekV  The idea sounds great to me. However the vscode extension may not have sufficient permission to verify whether the remote branch exists. For a private repo, the git link would always be 404 to the vscode extension even if the remote branch exists.

**Comment by IndrekV** [comment]
Thank you for the feedback. The limited permissions would block this check indeed so that's not going to work.

Another workaround would be to also provide menu items that point to the file in "master" branch that is present most of the times. (Or maybe a customizable default branch)

Something like:
- Go to Master branch online link

This might be an edge case that only I am having, but I'm struggling with this when jumping from one task to another and wanting to share links.

**Comment by teki** [comment]
GitLink is a similar IDEA plugin. It has a default remote and branch override, no logic is needed if it is set. I would be happy with something like that.

**Comment by qinezh** [comment]
@teki yeah, not sure if the default branch will resolve @IndrekV 's issue. Currently, `vscode-gitlink` already support default remote override, it's a good idea to add the default branch support. Please go head if you're interesting on it 😸
