### ISSUE TITLE
Look into using VScode clipboard API

### ISSUE THREAD

**Issue by cjs** [qinezh/vscode-gitlink#28]
Would it be possible to have this extension use the [VS Code Clipboard API](https://code.visualstudio.com/api/references/vscode-api#Clipboard) instead of https://www.npmjs.com/package/copy-paste? 

It would reduce the need for external libraries, and also simplify some situations where VS Code is running in a remote development environment.

**Comment by qinezh** [comment]
Thanks @cjs for the suggestion. Will take a look into it.

**Comment by qinezh** [comment]
The new version 0.7.0 has been released with the VS Code Clipboard API, please have a try. 

Thanks for the great suggestion again!

**Comment by cjs** [comment]
Confirmed working using vscode-insider and GitHub Codespaces. Thanks so much!
