### ISSUE TITLE
Add an example of <your_default_remote_source> in the doc?

### ISSUE THREAD

**Issue by dep** [qinezh/vscode-gitlink#30]
> Workspace Level: add gitlink.defaultRemote: "<your_default_remote_source>" in .vscode/settings.json under the root of your workspace.

This is great, but a bit unclear.  For `"<your_default_remote_source>"` an example might help.  Is it `https://github.com/foo/web.git`?  Is it `git@github.com:foo/web.git` ?

**Comment by qinezh** [comment]
@dep created a PR to update the doc.

**Comment by dep** [comment]
Thank you!
