### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by erenhatirnaz** [qinezh/vscode-gitlink#31]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _gitlink_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).
 
Additional info:
* This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by qinezh** [comment]
Closed as I have no bandwidth to maintain another marketplace version.

**Comment by LangLangBart** [comment]
@qinezh is it okay if I add your extension to the 'Auto Publishing' list ?

- Ref: https://github.com/EclipseFdn/publish-extensions/blob/master/extensions.json
- Ref: https://github.com/EclipseFdn/open-vsx.org/wiki/Auto-Publishing-Extensions

**EDIT:** They recommend to ask first:

> _If you are not the author, we suggest you first reach out to the author with an issue in their GitHub repo to request that they publish their extension to [open-vsx.org](https://open-vsx.org/) or add it to the auto-publish list._
