### ISSUE TITLE
Get gitlab url error with port number

### ISSUE THREAD

**Issue by wwsun** [qinezh/vscode-gitlink#35]
## Remote

```bash
git remote -v
origin	ssh://git@g.hz.corp.com:22222/tango/sample.git (fetch)
origin	ssh://git@g.hz.corp.com:22222/tango/sample.git (push)
```

## Gitlinks copy

Gitlinks generate the error url

```
https://g.hz.corp.com/22222/tango/blob/master/packages/core/src/models/file.ts#L182
```

## Expected

expect some way to ignore the port number

```
https://g.hz.corp.com/tango/sample/blob/master/packages/core/src/models/file.ts#L182
```

**Comment by qinezh** [comment]
@wwsun sorry for late response, the issue should be resolved in [v1.1.0](https://marketplace.visualstudio.com/items?itemName=qezhu.gitlink), please take a try. Also, feel free to reopen this issue if it doesn't work😄
