### ISSUE TITLE
bug when changes from local file has not been pushed

### ISSUE THREAD

**Issue by Xat59** [qinezh/vscode-gitlink#39]
Hi guys,

I am using your extension for the first time and discovered a bug when you use the extension on a file that has been edited localy, and not yet pushed.

Actualy, it uses the line number (or line number range) from the local file, even if the file has been edited localy. Of course, that causes a gap and line numbers are different on the remote and localy because of these local changes.

### How to reproduce

1/ get any existing repo that already has files
2/ in a file that has content, add some text at the first line without pushing it
3/ try to use GitLink on text or text block below the first line
4/ as you can see, it has a gap between the line you've actually GitLink'ed and the generated link

Maybe you could take in account the local changes to adapt the line numbers on the remote ?

Regards.

**Comment by qinezh** [comment]
> Maybe you could take in account the local changes to adapt the line numbers on the remote?

Thank you @Xat59 for the suggestion! 
However, the solution would be tricky. For your case (repro steps), the link with line number is still incorrect if the new added text are selected from the local, as the changes doesn't exist in remote...

**Comment by Xat59** [comment]
@qinezh actually it should not be able to return a link if the user is trying to GitLink a text that has not been pushed. GitLink should return a link **only when working on lines that exist remotely.**

What do you think ?

**Comment by qinezh** [comment]
> @qinezh actually it should not be able to return a link if the user is trying to GitLink a text that has not been pushed. GitLink should return a link **only when working on lines that exist remotely.**
> 
> What do you think ?

I don't think so. The restriction is too much and it will **block** common user usages such like sharing a link code snippet from remote.

**Comment by Xat59** [comment]
> > @qinezh actually it should not be able to return a link if the user is trying to GitLink a text that has not been pushed. GitLink should return a link **only when working on lines that exist remotely.**
> > What do you think ?
> 
> I don't think so. The restriction is too much and it will **block** common user usages such like sharing a link code snippet from remote.

In my opinion it makes no sense to GitLink a text that has not been pushed, because GitLink cannot deal with it on the remote side.
That's why I suggest GitLink to generate the link accordingly the selected text and regarding the remote branch .

### Step to reproduce the bug

1/ get any existing **repo that already has files pushed**.
2/ in a pushed file that has content, **add some text at the 1st line without pushing it**.
3/ try to use GitLink on text **below the 1st,** such as the 2nd line
4/ as you can see, it has a difference between the line you've actually GitLink'ed and what it is displayed on that link. You've asked GitLink to create a link of the 2nd line, but this 2nd line is actually the line 1 on the remote because of local changes.

The reason of this difference is because the generated link is based on local file that has not been pushed.
Did you try to reproduce the bug ? Please, just have a look.

I know that could be tricky to deal with this bug, but that's actually a bug.

Thanks.

**Comment by qinezh** [comment]
> it makes no sense to GitLink a text that has not been pushed, because GitLink cannot deal with it on the remote side.

For this particular extension, availability is more important than accuracy. Without accuracy, the link can still be fixed manually, while without availability, there's no chance to get a link.

Take a common scenario as an example:
1. Create a new git branch in local and prepare some code changes;
2. Generate an online link of existing code snippet to discuss with team member;
3. The link will be 404 as the new branch doesn't exist in remote;
4. Replace with the correct branch in above link manually and send the new link to team member;

For your solution, I have to push the new branch to remote otherwise I can't even get a link. That's what I say availability is more important than accuracy for this case.

**Comment by Xat59** [comment]
So sometimes users need to edit the link manually, that is not really practical. Anyway I understand your point of view.

**Comment by qinezh** [comment]
> So sometimes users need to edit the link manually, that is not really practical. Anyway I understand your point of view.

Yes, it's a trade-off. 

Appreciate for the discussion, closed the bug.
