### ISSUE TITLE
Support configure host type

### ISSUE THREAD

**Issue by xjj59307** [qinezh/vscode-gitlink#40]
It seems that the plugin chooses host type (github/gitlab/...) automatically by [matching](https://github.com/qinezh/vscode-gitlink/blob/main/packages/git-urls/src/host/hostBuilder.ts) remote url. It doesn't work well with self-host repositories which usually doesn't match any of them.

Can we let users configure its own source type? 

```
gitlink.hostType = "gitlab" 
```

**Comment by qinezh** [comment]
Great suggestion! Now the new version [1.2.3](https://marketplace.visualstudio.com/items?itemName=qezhu.gitlink) supports it, please take a try : )
