### ISSUE TITLE
Both GoTo online link and copy online link fail

### ISSUE THREAD

**Issue by ditkin** [qinezh/vscode-gitlink#44]
Version: 1.2.3
VSCode version: 1.66.2

Copy Online link fails with error:
`Can't find a matched host type for the url: <my repo>. You may be able to specify the host type to match it.`

GoTo Online link fails with error:
`Fail to copy the link null, error: Error processing argument at index 0, conversion failure from null`

Happy to provide any other information that might be useful!!

**Comment by Gepar** [comment]
Same error, VSCode 1.67.2.

**Comment by trevor-atlas** [comment]
Same here. Version: 1.67.2
OS: Darwin x64 20.6.0

**Comment by qinezh** [comment]
@ditkin Thanks for reporting the issue, would you please provide with the URL? Btw, you could replace the sensitive information with some placeholder like `foo`, `bar`.

**Comment by noman-land** [comment]
It appears the extension isn't recognizing self-hosted GitHub Enterprise urls behind login if **Host Type** is set to `auto`. Changing the setting explicitly to `github` worked for me:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/27938023/170572310-30ffdab3-e546-43d0-a97f-8d1fb0039be0.png">

**Comment by qinezh** [comment]
Version 1.2.4 is released for this bug fix, please have a try. Thank you all for reporting the issue😄
