### ISSUE TITLE
Support VSTS link.

### ISSUE THREAD

**Issue by lijunle** [qinezh/vscode-gitlink#5]
It could build the link for this:

![image](https://user-images.githubusercontent.com/1296500/27700304-c9e9de84-5d2f-11e7-9c5e-f323ec5a7a37.png)

I could help on implementing this if you want. 😃

**Comment by qinezh** [comment]
Hi @lijunle , it would be appreciated if you could help to contribute to this project. 😃

Currently, I plan to move the core logic to another project [GitLink](https://github.com/qinezh/gitlink), so people could get the ability through NPM.  vscode-gitlink would also use this package later. 

If you want to contribute to support VSTS link, could you go to [GitLink](https://github.com/qinezh/gitlink) and submit a PR?

**Comment by lijunle** [comment]
Sure thing!

2017年6月30日 15:10，"Qinen.Zhu" <notifications@github.com>写道：

**Comment by qinezh** [comment]
Please update to the latest version, it support VSTS now because of your contribution to [git-urls](github.com/qinezh/git-urls) 🌞

**Comment by lijunle** [comment]
Awesome! It will take a try!
