### ISSUE TITLE
Shorten the URL

### ISSUE THREAD

**Issue by lijunle** [qinezh/vscode-gitlink#6]
As you can guess, the URL with position can be very long. Integrate any shorten URL service into the pop up after copy could be a good solution.

Some well know shorten URL services:

- http://aka.ms/
- https://goo.gl/
- http://tinyurl.com/

**Comment by qinezh** [comment]
Yes, I think it's a good idea if we need share the URL with others.

**Comment by qinezh** [comment]
Some shorten URL services need `APIKEY` to avoid abuse. In another word, one needs this feature may need to apply for the apikey first, which is kind of too inconvenient...
