### ISSUE TITLE
After the recent update, the url is not correct

### ISSUE THREAD

**Issue by haccanri** [qinezh/vscode-gitlink#7]
I have been using this extension for a while and I love this extension for its simplicity and convinience.

I use a gitlab service inside my company with the url prefix gitlab.XXX.com, before the commit e8e955fa5ecd444116ea23cf7c3261f7de1ac43f, the extension can parse the url correctly from the gitconfig, but after this commit and the recent update, it does NOT work now. 

Please help me to fix it. I need this extension. Thanks very much!

**Comment by qinezh** [comment]
@haccanri Sorry for delay reply, I have fixed it in new version, could you help to update the extension and have a try?

**Comment by haccanri** [comment]
@qinezh , after updating, it works, thank you!
