### ISSUE TITLE
This feature has built in into VSCode

### ISSUE THREAD

**Issue by lijunle** [qinezh/vscode-gitlink#8]
Hi, @qinezh 

I found that, the open remote URL feature has been integrated into the newest version of VSCode.

![image](https://user-images.githubusercontent.com/1296500/29349856-98800bfa-828e-11e7-8b58-cd7990668264.png)

**Comment by qinezh** [comment]
@lijunle  Seems good news~

However, how to enable the feature in latest version of VSCode? I can't toggle the option as you mentioned...

**Comment by lijunle** [comment]
It is on the right-top "..." menu:

[image: Inline image 1]

You need to wait for few seconds after you open a new VSCode instance.

**Comment by qinezh** [comment]
@lijunle it's weird... I still can't enable the feature after updating vscode. Do you have related extension installed?

**Comment by lijunle** [comment]
@qinezh I finally figure out the reason why I saw that in my menu. That is from [Git Lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) plugin.
