### ISSUE TITLE
Highlighting on BitBucket links doesn't work

### ISSUE THREAD

**Issue by kbariotis** [qinezh/vscode-gitlink#9]
GitLink opens a page that ends like this:

`...package-lock.json?fileviewer=file-view-default#L13-L15`

but highlighting doesn work. If I click on a row, browser's URL changes to this:

`...package-lock.json?fileviewer=file-view-default#package-lock.json-13`

and for multiline highlighting, it takes comma separated line numbers like this:

`...package-lock.json?fileviewer=file-view-default#package-lock.json-13,14,15`.

Thank you

**Comment by qinezh** [comment]
@kbariotis I have already fixed the bug in latest version. Have a try~

**Comment by kbariotis** [comment]
@qinezh sweet! works like a charm! Thank you for this extension. :)
